### ISSUE TITLE
Mocking serializer: ListSerializer object is not callable

### ISSUE THREAD

**Issue by Fandekasp** [stphivos/django-mock-queries#91] opened 2018-09-14 06:25 UTC
In order to increase coverage, I'm trying to test my serializer methods, such as 

serializer
```py
from rest_framework import serializers
from app.models import Host, HostRole

class HostSerializer(serializers.ModelSerializer):
    hostrole_set = serializers.SerializerMethodField('get_main_hostrole')
    class Meta:
        model = Host
        fields = ('hostrole_set')

    def get_main_hostrole(self, host):
        qs = HostRole.objects.filter(role_type="main", host=host)
        serializer = HostRoleSerializer(instance=qs, many=True)
        return serializer.data
```

test
```py
from django.test import TestCase
from app.serializers import HostSerializer, HostRoleSerializer, HostRole
from django_mock_queries.query import MockSet, MockModel
from unittest.mock import patch



HOST = MockModel(pk=1)
HOST_ROLES = MockSet(
    MockModel(
        pk=1,
        host=1,
        roletype='main',
        name='Main role',
    ),
    MockModel(pk=2, host=HOST, role_type='sub', name='Sub role'),
    model=HostRole,
)

class HostSerializerTestCase(TestCase):
    @patch('app.serializers.hosts.HostRole', objects=HOST_ROLES)
    def test_get_main_hostrole(self, mock_objects):
        self.assertEqual(
            HostSerializer().get_main_hostrole(HOST),
            {
                'pk': 1,
                'host': 1,
                'roletype': 'main',
                'name': 'Main role',
            },
        )
```

this results on the test failing with
```
AssertionError: [] != {'pk': 1, 'host': 1, 'roletype': 'main', 'name': 'Main role'} 
```

If I try to replace `host=1` with `host=HOST` in the HOST_ROLES MockModel, it fails on 
`return serializer.data` with this error:
```
/usr/local/lib/python3.7/site-packages/rest_framework/serializers.py:514: in to_representation
    attribute = field.get_attribute(instance)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = PrimaryKeyRelatedField(read_only=True)
instance = {'pk': 1, 'host': {'pk': 1, 'save': <PropertyMock id='139917611941784'>, '_MockModel__meta': <django_mock_queries.quer...e_type': None, 'task': None, 'description': None, 'about': None,}

    def get_attribute(self, instance):
        if self.use_pk_only_optimization() and self.source_attrs:
            # Optimized case, return a mock object only containing the pk attribute.
            try:
                instance = get_attribute(instance, self.source_attrs[:-1])
>               value = instance.serializable_value(self.source_attrs[-1])
E               TypeError: 'NoneType' object is not callable

/usr/local/lib/python3.7/site-packages/rest_framework/relations.py:167: TypeError
```

Re-reading your doc, I tried using the assert_serializer method, but I'm unclear on the best way to use it. When adding a breakpoint after `serializer = HostRoleSerializer(instance=qs, many=True)`:
```py
ipdb> assert_serializer(serializer).instance(qs.first()).returns('pk', 'name').run()                      
*** TypeError: 'ListSerializer' object is not callable   
```
I just want my test to verify that the `HostSerializer.get_main_hostrole(HOST)` is gonna return the data from the host role with roletype='main'.

Did you spot a mistake in my test ? Or do you have a better idea on how to complete this test ? Thanks for the support

**Comment by stphivos** [comment] 2018-09-29 13:42
Hi @Fandekasp, sorry for the late reply :)

`MockModel` doesn't have Django base model's `serializable_value` [method](https://github.com/django/django/blob/cc79c7ee637e65c8da27e56d746c87903d5ec901/django/db/models/base.py#L630). It needs to be extended to support that. For this scenario you can use the original models. E.g.:

```python
from mock import patch
from django.test import TestCase
from django_mock_queries.asserts import assert_serializer
from django_mock_queries.query import MockSet

from app.models import Host, HostRole
from app.serializers import HostSerializer, HostRoleSerializer


class HostSerializerTestCase(TestCase):
    def test_host_serializer(self):
        host = Host(pk=1)
        r_main = HostRole(pk=1, host=host, role_type='main')
        r_sub = HostRole(pk=2, host=host, role_type='sub')

        with patch('api.models.HostRole.objects', MockSet(r_main, r_sub)):
            data = {
                # Using HostRoleSerializer directly here since that can have its own test(s)
                'hostrole_set': HostRoleSerializer([r_main], many=True).data
            }

            assert_serializer(HostSerializer) \
                .instance(host) \
                .returns('hostrole_set') \
                .values(**data) \
                .run()
```

**Comment by stphivos** [comment] 2018-10-09 13:00
Closing this now but feel free to reopen if the issue isn't resolved.

**Closed by stphivos** 2018-10-09 13:00 UTC
