### ISSUE TITLE
.create() method fails when model has foreign keys

### ISSUE THREAD

**Issue by luisiacc** [stphivos/django-mock-queries#142] opened 2021-06-04 17:18 UTC
When trying to create a mock model that has some PKs, it fails with:

`ValueError: Cannot assign "mock-pizza-1": "MyModel.pizzas" must be a "Pizza" instance`

Could have something to do with [this](https://github.com/stphivos/django-mock-queries/issues/114). Is there a good way to do this ? 

An implementation option would be to remove all relations from the `save` method, and putting them somewhere else, so when you try to access them, you access them from that place. This is a philosophy that is used in some DRF nested serializers.

**Comment by stefan6419846** [comment] 2024-04-19 14:56
@MartinGotelli At least the message looks like this. I am going to close this issue as saved. If this is indeed a different issue, re-opening the issue once there are more reproduction details should be no big deal.

**Closed by stefan6419846** 2024-04-19 14:56 UTC
